# Generated by Django 2.1 on 2018-10-02 17:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_auto_20181001_1749'),
        ('users', '0004_auto_20180928_2119'),
    ]

    operations = [
    ]
