# Generated by Django 2.1.2 on 2018-10-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181016_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('W', 'woman'), ('M', 'man'), ('O', 'other')], default='W', max_length=2),
        ),
    ]
