# Generated by Django 2.1.4 on 2019-01-08 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_chief', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_id', models.CharField(max_length=32)),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='cook',
            name='stove',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooks', to='stoves.Stove'),
        ),
    ]
