# Generated by Django 2.1.4 on 2019-01-04 22:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atomictiming',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
